laravel/tinker

src/Console/TinkerCommand.php

Psy Shell will, [by default](http://psysh.org/#all-the-options), check for updates on a weekly basis by making a [file_get_contents request to github](https://github.com/bobthecow/psysh/blob/master/src/Psy/VersionUpdater/GitHubChecker.php#L73). The first successful response will be cached.
However, on machines that don't have the ability to make external calls to the internet ( like intranet sites or those on otherwise proxied networks ), this feature causes the shell to hang for ( about ) 60 seconds on launch before you can do anything. Plus, because the response fails and doesn't cache, it'll happen every time.
I feel like this is a feature that doesn't really add much value, so this pull request disables it outright.
If you prefer to leave it as an option however, I have created two …

Disable psy shell update check

---

src/ClassAliasAutoloader.php
src/Console/TinkerCommand.php

This stops multiple instances of these classes remaining registred, so that future uses cause all of them to print to the shell and alias, which is not desirable.

Fixed subtle bugs

---

tests/TinkerCasterTest.php

Use PSR-1 while extending PHPUnit TestCase class. This will help us when to migrate to PHPUnit 6, that no longer support snake case namespaces.

[1.0] Use PSR-1 in PHPunit TestCase

---

config/tinker.php.stub
src/ClassAliasAutoloader.php
src/TinkerServiceProvider.php

Currently tinker class aliasing takes the first matching class alias based on alphabetical ordering. This works well in a lot of cases. However, there are cases when this logic isn't sufficient to allow selecting the correct alias, and can easily result in unhelpful aliases being generated. 
This PR introduces an (optional) config file that can be published with an artisan command:
```
php artisan vendor:publish --provider=Laravel\\Tinker\\TinkerServiceProvider --tag="config"
```
This config file contains an array option called `exclude_aliases` which can be populated with either fully-qualified class names to block specific classes being used for alias resolution, or namespace prefixes.
For example, in my current project I have the following structure:
- App
- Formatters
- Song
- App
- …

Introduce exclude_aliases option to allow classes to be excluded from class aliasing.

---

composer.json

Allows psysh 0.9.
---
You may ask, why now allow all 0.x series - well, we don't know if things will break. This is definitely safest, and not much effort to test each new minor 0.x release. Once we reach 1.x, we can safely allow any 1.x, as per semver.

Allow psysh 0.9

---

config/tinker.php
src/Console/TinkerCommand.php

This PR introduces an ability to register custom commands in Tinker. This allows users to create a standard Laravel console command and call it from Tinker.
Examples of use:
* query logger/debugger:
```
>>> debug_queries
>>> Order::first()->getReport()
Report #67: ...
>>> show_queries
There are 42 queries captured.
1. select * from order_categories;
2. select id from order_type where tag = 'internal';
...
```
* testing out auth-dependent commands:
```
>>> log_in
>>> auth()->user()->getProfilePicture()
```
And bunch of other cool things! Thanks

Ability to add custom commands

---

src/Console/TinkerCommand.php

After [the update to ServiceProviders](https://github.com/laravel/framework/commit/78b3fe6bdc6d8219c4b6aca5a160e27c9e65b3d8), the `basePath()` function in `Illuminate\Foundation\Application` was extended to support an additional parameter `$path`. This was not documented nor updated in [the contract](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Contracts/Foundation/Application.php#L21). When attempting to use `laravel/tinker` on a `laravel/framework` installation prior to v5.4.17, the following exception is thrown:
```
[Symfony\Component\Debug\Exception\FatalErrorException]
Laravel\Tinker\ClassAliasAutoloader::__construct(): Failed opening required '/data/projects/project' (include_path='.:/usr/share/php')
```
This commit relies on the `base_path` function which supports …

Add support for laravel/framework < v5.4.17

---

README.md

We're one year into auto-discovery now and anything <5.5 isn't supported anymore so we can start removing these notes.

Remove service provider docs

---

README.md

Resubmitting from laravel/docs PR.
I wasted half a day wondering why dispatching jobs wasn't working as expected. Turned out it was a combination of using tinker and the fact that dispatch method uses garbage collection to put jobs on the queue.
I filed this bug, which was closed, because two other where already filed concerning the same problem. Many people are wasting their time when faced with this problem, so it would make sense to document that "known subtlety" (citing Graham here).
Thanks.

Explain issues of dispatching jobs from tinker.

---

config/tinker.php

This isn't a bug, but something minor that I believe could be improved. Generally my use of the autoloader in Tinker is to perform database queries, as it saves you prefixing each model with `App\`. However, if you're also using Nova in your app all those classes will take precedence because of the order they are loaded.
```sh
>>> User::first()
[!] Aliasing 'User' to 'App\Nova\User' for this Tinker session.
PHP Fatal error:  Call to undefined method User::first() in Psy Shell code on line 1
>>> App\User::first()
```
The easiest fix here would be not to alias Nova classes - and I wonder if this might be considered for the default config rather than something you'd have to add yourself.
```php
'dont_alias' => [
'App\Nova'
],
```
Obviously it assumes your main namespace will be `App` for …

Don't alias App\Nova by default

---

README.md

This PR accompanies https://github.com/laravel/docs/pull/5654 to move the documentation to the docs repo so we have a single place where we can maintain it.

[2.x] Move docs to Laravel documentation

---

src/Console/TinkerCommand.php
src/TinkerCaster.php

Before:
```
>>> Illuminate\Mail\Markdown::parse("### test\n");
=> Illuminate\Support\HtmlString {#3811}
```
After:
```
>>> Illuminate\Mail\Markdown::parse("### test\n");
=> Illuminate\Support\HtmlString {#4008
html: "<h3>test</h3>\n",
}
```

[2.x] Add HtmlString caster

---

src/Console/TinkerCommand.php

This PR adds `--execute` option to the `php artisan tinker` command.
The idea is that by running `php artisan tinker --execute="dump(config('database'))"`, you can use tinker non-interactively.
This allows the user to use _tinker_ somewhat programmatically. It is **extremely** helpful in environments where an interactive shell is not available. **Laravel Vapor** for example. Debugging Vapor deployments becomes much easier.

[2.x] Add --execute option to console command

---

composer.json
src/Console/TinkerCommand.php

This PR forwards things like `--no-ansi` and `-vv` to psysh in the proper way, instead of ignoring them. Once this PR is merged, we can tag tinker v2.4.0.
// cc @bobthecow

[2.x] Forward input options to psysh

---

src/Console/TinkerCommand.php

1. Fixes incorrect implementation within https://github.com/laravel/tinker/pull/89. In particular this matters if the command is called by code or tests etc.
2. Fixes the shell exit code not getting forwarded.

Fixed execute not unregistering loader and exit code

---

.github/workflows/tests.yml

To be the same as the framework repos.

[2.x] Updated actions config

---

src/Console/TinkerCommand.php

When using tinker with the `execute` option, the output instance is missing on the $shell instance. Causing tinker not being able to show exceptions to the user. You can quickly reproduce this bug in a fresh Laravel application like so:
```
php artisan tinker --execute="throw new Exception('Foo');"
``` 
Gives the following error: `Error: Call to a member function writeln() on null`.
After this chance, you will get the expected output: `Exception with message 'Foo'`.

[2.x] Fixes missing output while using execute option

---

tests/ClassAliasAutoloaderTest.php

- According to the [PHPUnit fixtures reference](https://phpunit.readthedocs.io/en/8.5/fixtures.html#more-setup-than-teardown), it should be `protected function setUp(): void` and `protected function tearDown(): void` methods.

Imprive PHPUnit fixtures

---

README.md

Shields.io works a lot better than the old pugx.org.

[2.x] Update the badges to use shields.io

---

.gitattributes
.github/workflows/tests.yml
CHANGELOG.md
composer.json
phpunit.xml.dist

This allows Testbench to properly require `laravel/laravel` 9.x on PHP 8.

 Sync develop with code from 2.x branch (reserved all commits)

---

.github/workflows/tests.yml
composer.json

Used to prepare integration tests for Laravel 9

Support `symfony/var-dump` v6 for Laravel 9

---

src/Console/TinkerCommand.php

as migrate depends on migrate:install to prepare database
In response to #136

Add migrate:install to whitelisted commands

---

src/Console/TinkerCommand.php

In #144 we solved the issue that none of the existing artisan commands were working anymore in Tinker. An additional fix is needed to set the Laravel app instance on the resolved commands so custom commands can keep on 
working. We can achieve this with how the original `resolve` method worked before the lazy load changes by using the `add` method that'll set the Laravel instance.
Fixes https://github.com/laravel/tinker/issues/145

Add Laravel app instance to command

---

src/Console/TinkerCommand.php
src/TinkerCaster.php

As I just made this change in Tinkerwell myself, I thought it would be nice to contribute this to tinker as well.
This PR adds the ability to cast the new `Illuminate\Process\ProcessResult` objects when running them inside of tinker.
Without this PR:
With casting:

Cast ProcessResult objects

---

.gitattributes
.github/workflows/static-analysis.yml
composer.json
phpstan.neon.dist
src/TinkerCaster.php

This pull request adds type checking to this repository.

[2.x] Adds type checking

---

src/Console/TinkerCommand.php

This PR modifies the behaviour of the `--execute` option to have it return an exit code of 1 when an exception is thrown.
Currently all exceptions are caught and rendered by Psysh internally, which makes it difficult to determine whether the command succeeded.
[Original PR](https://github.com/laravel/tinker/pull/163)
Reopened on master branch as per https://github.com/laravel/tinker/pull/163#issuecomment-1628516836

[3.x] Return correct exit code on exceptions

---

composer.json

Tested locally against 2.x, confirmed support with upcoming PHP-Parser 5.x.
This shouldn't break backwards compatibility in any way, as the major change was dropping support for PHP versions so old that Laravel hasn't thought about them in years :)

Update PsySH dependency to v0.12

---

.github/workflows/tests.yml
composer.json
phpunit.xml.dist

Packagist stated indicate low usage from older PHP version so it should good to remove support for older version.

[3.x] Remove supports for PHP 8.0 and 7.x
